apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: element47
      defaultBucket: sma_engine
      tlsSkipVerify: true
    secureJsonData:
      token: element47-dev-token
    editable: true
